"""Schema contract: raw column names/types, canonical names, and modelling rules."""

from __future__ import annotations

from collections.abc import Mapping
from enum import StrEnum
from functools import cache
from importlib import resources

import yaml
from pydantic import BaseModel, model_validator


class ModelUse(StrEnum):
    ENTITY = "entity"
    FEATURE = "feature"
    DERIVE = "derive"
    PROVENANCE = "provenance"
    EXCLUDE = "exclude"


class Confidence(StrEnum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    UNKNOWN = "unknown"


class Column(BaseModel):
    raw: str
    name: str
    type: str
    model_use: ModelUse
    confidence: Confidence
    meaning: str
    # True only once the meaning is confirmed from the exporter/collector documentation.
    # Profiling evidence raises `confidence`; it never sets `validated`.
    validated: bool = False

    @model_validator(mode="after")
    def _uncertain_columns_are_not_features(self) -> Column:
        if self.model_use is ModelUse.FEATURE and self.confidence in (Confidence.LOW, Confidence.UNKNOWN):
            raise ValueError(f"{self.raw}: {self.confidence} confidence columns cannot be model features")
        return self


class Contract(BaseModel):
    schema_version: int
    name: str
    columns: list[Column]

    @property
    def raw_names(self) -> list[str]:
        return [c.raw for c in self.columns]

    def duckdb_types(self) -> dict[str, str]:
        """Explicit raw-column types for read_csv, so no per-file type inference."""
        return {c.raw: c.type for c in self.columns}

    def rename_select(self, exprs: Mapping[str, str] | None = None) -> str:
        """SQL select list that casts and renames raw columns to canonical names.

        `exprs` maps a raw column to its own value expression, replacing the plain CAST.
        """
        exprs = exprs or {}

        def value(c: Column) -> str:
            return exprs.get(c.raw) or f'CAST("{c.raw}" AS {c.type})'

        return ",\n  ".join(f'{value(c)} AS "{c.name}"' for c in self.columns)

    def check_columns(self, found: list[str]) -> tuple[list[str], list[str]]:
        """Return (missing, unexpected) raw columns for a file's header."""
        expected = set(self.raw_names)
        present = set(found)
        return sorted(expected - present), sorted(present - expected)

    def to_markdown(self) -> str:
        """Render SCHEMA.md. The YAML contract is the source of truth; never edit SCHEMA.md by hand."""
        def cell(text: str) -> str:
            return text.replace("|", "\\|")

        rows = [
            f"| `{c.raw}` | `{c.name}` | {c.type} | {'yes' if c.validated else '**UNVERIFIED**'} | {c.confidence} "
            f"| {'**DO NOT USE FOR FEATURES**' if c.model_use is ModelUse.EXCLUDE else c.model_use} | {cell(c.meaning)} |"
            for c in self.columns
        ]
        n_valid = sum(c.validated for c in self.columns)
        return "\n".join([
            f"# Schema: {self.name} (version {self.schema_version})",
            "",
            ("<!-- GENERATED by `uv run netanomaly docs` from src/netanomaly/contracts/"
            f"{self.name}.yaml. Do not edit by hand; tests fail if this file is stale. -->"),
            "",
            (f"**{n_valid} of {len(self.columns)} fields are validated** against exporter/collector documentation. "
            "Every other meaning is an inference from field names, NetFlow/IPFIX conventions and data profiling."),
            "",
            "- **validated**: meaning confirmed from the collector's documentation.",
            "- **confidence**: strength of the *inference* (high / medium / low / unknown). Only high/medium may feed features.",
            ("- **use**: entity (grouping key), feature, derive (input to derived columns), provenance (traceability only), "
            "exclude."),
            "",
            "| raw column | canonical | type | validated | confidence | use | meaning / evidence |",
            "|---|---|---|---|---|---|---|",
            *rows,
            "",
        ])


@cache
def load_contract(name: str = "netflow_v1") -> Contract:
    text = resources.files("netanomaly.contracts").joinpath(f"{name}.yaml").read_text(encoding="utf-8")
    contract = Contract.model_validate(yaml.safe_load(text))
    names = [c.name for c in contract.columns]
    if len(set(names)) != len(names) or len(set(contract.raw_names)) != len(contract.raw_names):
        raise ValueError("schema contract has duplicate column names")
    return contract
